Django/Inventory-Control-main/inventory_control/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views.category import CategoryList, CategoryDetail

app_name = "api"
urlpatterns = [
    path("categories/", CategoryList.as_view()),
    path("categories/<int:pk>/", CategoryDetail.as_view())
]

urlpatterns = format_suffix_patterns(urlpatterns)

Django/Inventory-Control-main/inventory_control/inventory_control/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fornecedores/', include('suppliers.urls')),
    path('produtos/', include('products.urls')),
    path('', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/Inventory-Control-main/inventory_control/users/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views
from .views import UserLoginView, UserLogoutView

app_name = "users"
urlpatterns = [
    path("", RedirectView.as_view(url="/login/", permanent=True)),
    path("usuarios/", views.index, name="index"),
    path("usuarios/cadastro/", views.create, name="create"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("usuarios/<str:username>/", views.update, name="update"),
    path("usuarios/<int:id>/delete/", views.delete, name="delete"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
]

Django/Inventory-Control-main/inventory_control/users/models.py
from django.db import models

# Create your models here.

Django/Inventory-Control-main/inventory_control/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import validate_email

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "password", "is_active"]
        widgets = {
            "password": forms.PasswordInput()
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True
        
    def save(self, commit=True):
        password = self.cleaned_data.get("password")
        
        user = super().save(commit=False)
        
        # Hash da senha
        if password:
            user.set_password(password)
            
        if commit:
            user.save()
            
        return user
    
    def clean(self):
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        
        if first_name == last_name:
            self.add_error("first_name", ValidationError("O primeiro nome não pode ser igual ao último nome"))
            self.add_error("last_name", ValidationError("O primeiro nome não pode ser igual ao último nome"))
            
            
        username = self.cleaned_data.get("username")
        
        try:
            validate_email(username)
        except ValidationError:
            self.add_error("username", ValidationError("Informe um endereço de e-mail válido"))
            
        return super().clean()

Django/Inventory-Control-main/inventory_control/users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from .forms import UserForm
from django.contrib.auth.views import LoginView, LogoutView

# Create your views here.


@login_required
def index(request):
    users = User.objects.all().order_by("-id")

    context = {
        "users": users
    }

    return render(request, 'users/index.html', context)


@login_required
def create(request):
    form_action = reverse("users:create")

    # POST
    if request.method == "POST":
        form = UserForm(request.POST)

        if form.is_valid():
            form.save()

            messages.success(request, "O usuário foi cadastrado com sucesso!")

            return redirect("users:index")

        context = {
            "form": form,
            "form_action": form_action
        }

        return render(request, "users/create.html", context)

    # GET
    form = UserForm()

    context = {
        "form": form,
        "form_action": form_action
    }

    return render(request, "users/create.html", context)


@login_required
def update(request):
    return render(request, "users/create.html")


@login_required
def delete(request, id):
    user = get_object_or_404(User, pk=id)

    user.delete()

    return redirect("users:index")


class UserLoginView(LoginView):
    template_name = "users/login.html"
    redirect_authenticated_user = True
    next_page = "products:index"


class UserLogoutView(LogoutView):
    next_page = "users:login"
    

Django/Inventory-Control-main/inventory_control/users/templates/users/create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  Usuários
{% endblock %}
{% block content %}
{% with create_url="/usuarios/cadastro/" %}
  {% if form_action == create_url %}
    <h2 class="mb-3">Cadastro de Usuários</h2>
  {% else %}
    <h2 class="mb-3">Edição de Usuários</h2>
  {% endif %}
    <form action="{{ form_action }}" method="post">
      {% csrf_token %}
      
      {{ form|crispy }}

      <div class="d-grid">
        <button class="btn btn-primary btn-lg">Salvar</button>
      </div>
    </form>
  {% endwith %}
{% endblock %}

Django/Inventory-Control-main/inventory_control/users/templates/users/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Usuários
{% endblock %}
{% block head %}
<script src="{% static 'base/js/index.js' %}"></script>
{% endblock %}
{% block content %}
  <h2 class="mb-3">Usuários</h2>

  <a
    href="{% url 'users:create' %}"
    title="Cadastrar novo usuário"
    class="btn btn-primary btn-sticky-bottom">
    <i class="bi bi-plus"></i>
  </a>

  {% comment %}Filtro{% endcomment %}
  <form action="" class="row mb-3">
    <div class="col">
      <input class="form-control" type="text" name="q" placeholder="Buscar" />
    </div>
    <div class="col-auto">
      <button type="submit" class="btn btn-primary">Buscar</button>
    </div>
  </form>

  {% comment %}Tabela de estoque{% endcomment %}
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Username</th>
          <th>Ativo</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.first_name|title }} {{ user.last_name|title }}</td>
            <td>{{ user.username }}</td>
            <td>
              <input {% if user.is_active %}checked{% endif %} type="checkbox" class="form-check-input" />
            </td>
            <td class="d-flex gap-1">
              <a href="{% url 'users:update' user.username %}" class="btn btn-warning btn-sm" title="Editar usuário"><i class="bi bi-pencil"></i></a>
              <form method="post" action="{% url 'users:delete' user.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-sm" title="Remover usuário"><i class="bi bi-trash"></i></button>
              </form>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="8" class="text=center">Nenhum usuário cadastrado</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% if users.paginator.num_pages > 1 %}
      <nav aria-label="Paginação da página">
        <ul class="pagination justify-content-end">
          {% if users.has_previous %}
            <li class="page-item">
              <a href="?page={{ users.previous_page_number }}" class="page-link" aria-label="Anterior">&laquo;</a>
            </li>
          {% endif %}
          <li class="page-item active">
            <span class="page-link">{{ users.number }}</span>
          </li>
          {% if users.has_next %}
            <li class="page-item">
              <a href="?page={{ users.next_page_number }}" class="page-link" aria-label="Próximo">&raquo;</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
  </div>
{% endblock %}

Django/Inventory-Control-main/inventory_control/users/templates/users/login.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IStock - Login</title>
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}" />
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mt-5">
                    <div class="card-header">
                        <h2>Login</h2>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'users:login' %}" method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input type="hidden" name="next" value={{ next|default_if_none:"" }}>
                            {% include "partials/_submit_button.html" with text="Teste" loading_text="Tá carregando uai" %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>